# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spinningnotes
  name: spinningnotes-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "configmaps"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: spinningnotes-role-binding
  namespace: spinningnotes
subjects:
  - kind: ServiceAccount
    name: spinningnotes-service-account
    namespace: default
roleRef:
  kind: Role
  name: spinningnotes-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinningnotes-service-account
  namespace: spinningnotes