apiVersion: v1
kind: Service
metadata:
  name: spinningnotes-auth-service
  namespace: spinningnotes
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spinningnotes-auth
  type: ClusterIP